import crypto from 'node:crypto';

const encoder = new TextEncoder();
function base64url(input){return Buffer.from(input).toString('base64url')}
function safeEqualText(a='',b=''){const ha=crypto.createHash('sha256').update(String(a)).digest();const hb=crypto.createHash('sha256').update(String(b)).digest();return crypto.timingSafeEqual(ha,hb)}
function getSessionSecret(){const secret=process.env.SESSION_SECRET||'';if(secret.length<32)throw new Error('SESSION_SECRET must be at least 32 characters');return secret}
export function verifyAdminPassword(password){const expected=process.env.ADMIN_PASSWORD||'';if(!expected)throw new Error('ADMIN_PASSWORD is not configured');return safeEqualText(password,expected)}
export function createSessionToken(ttlSeconds=7200){const now=Math.floor(Date.now()/1000);const payload={sub:'site-admin',iat:now,exp:now+ttlSeconds,nonce:crypto.randomBytes(10).toString('hex')};const body=base64url(JSON.stringify(payload));const sig=crypto.createHmac('sha256',getSessionSecret()).update(body).digest('base64url');return{token:`${body}.${sig}`,expiresAt:payload.exp*1000}}
export function verifySessionToken(token=''){const [body,signature]=String(token).split('.');if(!body||!signature)return null;const expected=crypto.createHmac('sha256',getSessionSecret()).update(body).digest('base64url');if(!safeEqualText(signature,expected))return null;try{const payload=JSON.parse(Buffer.from(body,'base64url').toString('utf8'));const now=Math.floor(Date.now()/1000);if(payload.sub!=='site-admin'||!payload.exp||payload.exp<=now)return null;return payload}catch{return null}}
export function bearerFrom(request){const auth=request.headers.get('authorization')||'';return auth.toLowerCase().startsWith('bearer ')?auth.slice(7).trim():''}
export function allowedOrigin(request){const origin=request.headers.get('origin')||'';const configured=(process.env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean);if(!configured.length||!origin)return '';return configured.includes(origin)?origin:''}
export function corsHeaders(request){const origin=allowedOrigin(request);const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};if(origin)headers['Access-Control-Allow-Origin']=origin;return headers}
export function json(request,data,status=200){return new Response(JSON.stringify(data),{status,headers:corsHeaders(request)})}
export function preflight(request){const headers=corsHeaders(request);if(!headers['Access-Control-Allow-Origin'])return json(request,{ok:false,error:'Origin not allowed'},403);return new Response(null,{status:204,headers})}
export function requireAllowedOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;return Boolean(allowedOrigin(request))}
export function validateResumeData(data){if(!data||typeof data!=='object')return '简历资料格式不是对象';if(!data.profile||typeof data.profile!=='object')return '缺少 profile';if(!String(data.profile.name||'').trim())return '中文姓名不能为空';for(const key of ['experience','education','projects','skills','achievements'])if(!Array.isArray(data[key]))return `缺少数组字段 ${key}`;if(encoder.encode(JSON.stringify(data)).length>500_000)return '简历资料超过 500KB 限制';return ''}
export function validateAIProjects(items){if(!Array.isArray(items))return 'AI 作品库必须是数组';if(items.length>200)return 'AI 作品数量超过 200 条限制';const ids=new Set();for(const [i,p] of items.entries()){if(!p||typeof p!=='object')return `AI 作品第 ${i+1} 项格式错误`;const id=String(p.id||'').trim();const title=String(p.title||'').trim();if(!id||!title)return `AI 作品第 ${i+1} 项缺少 id 或 title`;if(ids.has(id))return `AI 作品 ID 重复：${id}`;ids.add(id);const path=String(p.path||'').trim();if(!p.externalUrl&&!path)return `AI 作品「${title}」缺少项目目录 path`;if(path.startsWith('/')||path.includes('..'))return `AI 作品「${title}」的 path 只能是 projects 下的相对目录名`;}
if(encoder.encode(JSON.stringify(items)).length>500_000)return 'AI 作品库超过 500KB 限制';return ''}
